import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/modules/Navbar/Navbar";
import Footer from "@/component/modules/Footer/Footer";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
      <body className={inter.className}>
        <div>
        <div className=" border-solid border-b-4 border-secondary1 bg-primary1 fixed top-0 left-0 right-0 z-50 ">
      <Navbar />
    </div>
          <main>{children}</main>
        </div>
        <Footer />
      </body>
      </Providers>
    </html>
  );
}
